[package]
name = "brine_proto"
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = { version = "0.17.3", default-features = false, features = ["bevy_state", "bevy_log"] }
bevy_ecs = "0.17.3"
uuid = { version = "1.18.1", features = ["v4"] }

brine_chunk = { path = "../brine_chunk" }
