[package]
name = "brine_chunk"
version = "0.0.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
minecraft-varint = "0.2"
thiserror = "2.0.17"
tracing = "0.1.41"

[dev-dependencies]
steven_protocol = { path = "../../third_party/stevenarella/protocol/", default-features = false }
